AllCops:
  Exclude:
    - Guardfile
    - db/**
    - db/migrate/**
    - lib/splitter/full_name.rb

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - app/helpers/**/*

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - config/**/*
    - spec/**/*
    - lib/tasks/**/*

Documentation:
  Enabled: false
