image: ruby:2.4.2

pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - export RAILS_ENV=test
          - export DATABASE_URL=postgresql://test_user:test_user_password@localhost/pipelines
          - bundle install
          - bundle exec rake db:test:prepare
          - bundle exec rspec
        services:
          - database

definitions:
  services:
    database:
      image: postgres
      environment:
        POSTGRES_DB: 'pipelines'
        POSTGRES_USER: 'test_user'
        POSTGRES_PASSWORD: 'test_user_password'
  caches:
    bundler: ./vendor
